import type {Metadata} from "next";
import {Inter} from "next/font/google";

import {ClerkProvider} from "@clerk/nextjs";

import {Toaster} from "sonner";

import "./globals.css";
import ModalProvider from "@/components/modals/modal-provider";
import {ThemeProvider} from "@/components/theme-provider";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: {
    default: "Shopsphere",
    template: "%s | Shopsphere",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme={"light"}
            enableSystem
            storageKey="shop-sphere"
            disableTransitionOnChange
          >
            <ModalProvider />
            <Toaster />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
