/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/DUjk5nP1UCH
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function AddProduct() {
  return (
    <Card className="w-full">
      <CardHeader className="flex flex-row space-y-0 items-start gap-2">
        <div className="grid gap-1">
          <CardTitle>Add Product</CardTitle>
          <CardDescription>Ready to add a new product?</CardDescription>
        </div>
        <div className="text-3xl ml-auto font-bold">$0.00</div>
      </CardHeader>
      <CardContent>
        <form className="grid gap-4 md:gap-6">
          <div className="grid gap-2">
            <Label className="text-base" htmlFor="name">
              Product Name
            </Label>
            <Input className="w-full" id="name" placeholder="Enter product name" type="text" />
          </div>
          <div className="grid gap-2">
            <Label className="text-base" htmlFor="price">
              Price
            </Label>
            <Input className="w-full" id="price" placeholder="Enter price" type="number" />
          </div>
          <div className="grid gap-2">
            <Label className="text-base" htmlFor="category">
              Category
            </Label>
            <Select defaultValue="Select category">
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select category" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="electronics">Electronics</SelectItem>
                <SelectItem value="clothing">Clothing</SelectItem>
                <SelectItem value="accessories">Accessories</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="grid gap-2">
            <Label className="text-base" htmlFor="description">
              Description
            </Label>
            <Textarea className="w-full" id="description" placeholder="Enter product description" />
          </div>
          <div className="grid gap-2">
            <Label className="text-base" htmlFor="image">
              Image URL
            </Label>
            <Input className="w-full" id="image" placeholder="Enter image URL" type="text" />
          </div>
          <div className="flex flex-col gap-2 lg:flex-row">
            <Button size="lg">Add Product</Button>
            <Button size="lg" variant="outline">
              Cancel
            </Button>
          </div>
        </form>
      </CardContent>
    </Card>
  )
}
